### ISSUE TITLE
Updates when deleting lines from global attribute files not written

### ISSUE THREAD

**Issue by dvalters** [dvalters/fuse-netcdf#37]
You can append lines to an attribute file, but trying to remove these extra lines appears to have no effect on the netcdf file. (The write operation appears to complete successfully but re-opening the attribute files shows it has not had the desired effect (The old lines are still there)

From #36

**Comment by blazk** [comment]
I just had this problem as well :-O

**Comment by dvalters** [comment]
It's the same for editing dimension variables too:

Mount a file and edit `DATA_REPR` for `latitude` in vim (for example)

Change the first line from `90.0` to `89.0`
save and exit vim
(Nothing suspicious reported in debug mode?)

`ncdump FILE -v latitude`:

```
 latitude = 90, 87.5, 85, 82.5, 80, 77.5, 75, 72.5, 70, 67.5, 65, 62.5, 60,   <-- no change!
    57.5, 55, 52.5, 50, 47.5, 45, 42.5, 40, 37.5, 35, 32.5, 30, 27.5, 25, 
    22.5, 20, 17.5, 15, 12.5, 10, 7.5, 5, 2.5, 0, -2.5, -5, -7.5, -10, -12.5, 
    -15, -17.5, -20, -22.5, -25, -27.5, -30, -32.5, -35, -37.5, -40, -42.5, 
    -45, -47.5, -50, -52.5, -55, -57.5, -60, -62.5, -65, -67.5, -70, -72.5, 
    -75, -77.5, -80, -82.5, -85, -87.5, -90 ;
}
```

**Comment by blazk** [comment]
I guess it's because "truncate" function is not implemented (does nothing).
I'm trying to implement truncate  code for attributes now to see if it fixes the issue

**Comment by blazk** [comment]
no,sorry I think it is different from what you describe, when I use Vim to edit attribute by deleting a line and save and open again, the contents of the attribute are different, but there is garbage at the end of attribute (like if file was not truncated)

**Comment by blazk** [comment]
Before my last pull request I could not save my Vim edits to attribute at all because "truncate()" call was failing. Maybe try merging master into your variable editing branch and see if that helps with what you describe ?

**Comment by dvalters** [comment]
No I merged the branches into master but doesn't seem to fix it - also there is traceback error from the truncate call now when editing a file:

```
open(u'/latitude/DATA_REPR', 32769)
getxattr(u'/latitude/DATA_REPR', u'security.capability')
getxattr(u'/latitude/DATA_REPR', u'security.capability')
removexattr(u'/latitude/DATA_REPR', u'security.capability')
truncate(u'/latitude/DATA_REPR', 0, 0L)
Uncaught exception from FUSE operation ftruncate, returning errno.EINVAL.
Traceback (most recent call last):
  File "/home/dav/devel/fusepy/fuse.py", line 715, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/dav/devel/fusepy/fuse.py", line 995, in ftruncate
    length, fh)
  File "/home/dav/devel/fusepy/fuse.py", line 1057, in __call__
    return getattr(self, op)(*args)
  File "../fusenetcdf/fusenetcdf.py", line 662, in newfunc
    result = attr(*args, **kwargs)
TypeError: truncate() takes exactly 3 arguments (4 given)
getxattr(u'/latitude/DATA_REPR', u'security.capability')
getxattr(u'/latitude/DATA_REPR', u'security.capability')
removexattr(u'/latitude/DATA_REPR', u'security.capability')
getattr(u'/latitude/DATA_REPR', None)
write(u'/latitude/DATA_REPR', '89.000000\n87.5
```

**Comment by blazk** [comment]
@dvalters I just pulled your current master and tried to edit DATA_REPR of latitude, I cannot write the file because I get the error:
```write(u'/latitude/DATA_REPR', '89.000000\n87.500000\n85.000000\n82.500000\n80.000000\n77.500000\n75.000000\n72.500000\n70.000000\n67.500000\n65.000000\n62.500000\n60.000000\n57.500000\n55.000000\n52.500000\n50.000000\n47.500000\n45.000000\n42.500000\n40.000000\n37.500000\n35.000000\n32.500000\n30.000000\n27.500000\n25.000000\n22.500000\n20.000000\n17.500000\n15.000000\n12.500000\n10.000000\n7.500000\n5.000000\n2.500000\n0.000000\n-2.500000\n-5.000000\n-7.500000\n-10.000000\n-12.500000\n-15.000000\n-17.500000\n-20.000000\n-22.500000\n-25.000000\n-27.500000\n-30.000000\n-32.500000\n-35.000000\n-37.500000\n-40.000000\n-42.500000\n-45.000000\n-47.500000\n-50.000000\n-52.500000\n-55.000000\n-57.500000\n-60.000000\n-62.500000\n-65.000000\n-67.500000\n-70.000000\n-72.500000\n-75.000000\n-77.500000\n-80.000000\n-82.500000\n-85.000000\n-87.500000\n-90.000000\n', 0, 0L)
Checking if global attr: latitude
Path is a DIMENSION VARIABLE: /latitude/DATA_REPR
Write buffer is of type: <type 'str'>
Converting write buffer to numpy array.
New array to append to VARIABLE /latitude/DATA_REPR is of TYPE: <type 'numpy.ndarray'>,Numpy DTYPE: float64
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 604, in write
    offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "fusenetcdf/fusenetcdf.py", line 662, in newfunc
    result = attr(*args, **kwargs)
  File "fusenetcdf/fusenetcdf.py", line 725, in write
    return self.ncfs.write(path, buf, offset, fh)
  File "fusenetcdf/fusenetcdf.py", line 600, in write
    dimvar[offset:offset+len(buf)] = newdimvar
  File "netCDF4/_netCDF4.pyx", line 3996, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:43651)
  File "netCDF4/_netCDF4.pyx", line 4208, in netCDF4._netCDF4.Variable._put (netCDF4/_netCDF4.c:45531)
RuntimeError: NetCDF: Operation not allowed in define mode
```

**Comment by dvalters** [comment]
Oh interesting - I had that error a while ago, but closed this issue because I could not reproduce it again:

Issue: https://github.com/dvalters/fuse-netcdf/issues/28

**Comment by blazk** [comment]
@dvalters do you get any "truncate" traceback error when editing attribute?

**Comment by dvalters** [comment]
Yes I get the same:

This for a variable's attribute:
```
open(u'/blh/newattr', 32769)
getxattr(u'/blh/newattr', u'security.capability')
getxattr(u'/blh/newattr', u'security.capability')
removexattr(u'/blh/newattr', u'security.capability')
truncate(u'/blh/newattr', 0, 0L)
Uncaught exception from FUSE operation ftruncate, returning errno.EINVAL.
Traceback (most recent call last):
  File "/home/dav/devel/fusepy/fuse.py", line 715, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/dav/devel/fusepy/fuse.py", line 995, in ftruncate
    length, fh)
  File "/home/dav/devel/fusepy/fuse.py", line 1057, in __call__
    return getattr(self, op)(*args)
  File "../fusenetcdf/fusenetcdf.py", line 662, in newfunc
    result = attr(*args, **kwargs)
TypeError: truncate() takes exactly 3 arguments (4 given)
getxattr(u'/blh/newattr', u'security.capability')
getxattr(u'/blh/newattr', u'security.capability')
removexattr(u'/blh/newattr', u'security.capability')
getattr(u'/blh/newattr', None)
Checking if global attr: blh
write(u'/blh/newattr', 'foobazbar\n', 0, 0L)
```

**Comment by blazk** [comment]
@dvalters I don't understand why your code is calling truncate with three parameters
```
...
truncate(u'/blh/newattr', 0, 0L)
...
```
 In my debug output truncate is called with two parameters:
```
...
open(u'/blh/long_name', 32769)
getxattr(u'/blh/long_name', u'security.capability')
getxattr(u'/blh/long_name', u'security.capability')
removexattr(u'/blh/long_name', u'security.capability')
truncate(u'/blh/long_name', 0)
getattr(u'/blh/long_name', None)
Checking if global attr: blh
getxattr(u'/blh/long_name', u'security.capability')
getxattr(u'/blh/long_name', u'security.capability')
...
```

**Comment by blazk** [comment]
ok, glad to hear truncate() is now working for you!
Does it mean your variable editing also works?
(unfortunatelly I cannot get past the "not permitted in define mode" error" to test it).

**Comment by dvalters** [comment]
Unfortunately no :(
There are no errors in debug mode  or with saving/editing from vim, it just doesn't appear to change the file

**Comment by dvalters** [comment]
Superseded by #42 after merging #41
